## Step 1:
    Load in original data CSV
    
    In this case we will be using a CVS file comprised of county puclic health data in the United States

## Step 2:
    Load in pandas and numpy using functions:
    
    import pandas as pd & import numpy as np

In [1]:
import pandas as pd

In [2]:
import numpy as np

## Step 3:
    Create data frame (df) value using this code:
    
    df=pd.read_csv("CHD.csv")

In [15]:
    df=pd.read_csv("CHD.csv")

## Step 4:
    This analysis will compare the rate of excessive drinking to the rate of premature death in order to determine if the two data points have significant correlation.
    
    In order to gather the first data point we will use the function:
    
df.loc[:, ["State", "County", "Excessive drinking", "Premature death"]].sample(n=20)

In [31]:
df.loc[:, ["State", "County", "Excessive drinking", "Premature death"]].sample(n=20)

     State                        County  Excessive drinking  Premature death
1883    KS                 Pawnee County               0.109           8553.0
2832    MO              Gasconade County               0.148           9243.0
1534    IL             Stephenson County               0.227           7325.0
5600    VA             Montgomery County               0.139           5876.0
5860    WI                   Iron County               0.302           7210.0
2079    KY                  Lewis County               0.126          10418.0
3758    NM                 Chaves County               0.153           9779.0
1658    IN                 Marion County               0.157           9042.0
3252    NC                   Ashe County               0.086           7900.0
9       AK  Fairbanks North Star Borough               0.200           5862.0
1586    IN               Crawford County                 NaN          10583.0
4285    OK               Sequoyah County               0.103          10371.0
4240    OK                  Mayes County               0.080          10403.0
420     CA                 Plumas County               0.183           7082.0
2495    MI                Jackson County               0.219           7102.0
1609    IN               Franklin County               0.220           7276.0
6091    WY                   Park County               0.154           6597.0
1957    KY                   Bell County                 NaN          13418.0
2782    MO                 Butler County               0.113          10012.0
3193    MT        Lewis and Clark County               0.179           6405.0

## Step 5:
    Now that we have teh data side by side and can compare, we can create a new series based on the data and export this file as a CSV using function:
    
    .to_csv

In [38]:
series1 = df.loc[:, ["State", "County", "Excessive drinking", "Premature death"]].sample(n=20)

In [39]:
series1.to_csv("series1.csv")